name: Keep Server Alive

on:
  schedule:
    - cron: "*/14 * * * *" # Runs every 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Ping the website
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://reforestation-management.onrender.com/
