name: Ensure Site is Fully Loaded

on:
  schedule:
    - cron: "*/8 * * * *"  # Runs every 14 minutes
  workflow_dispatch:

jobs:
  check-load:
    runs-on: ubuntu-latest

    steps:
    - name: Ensure the site is fully loaded
      run: |
        # Wait for the page to fully load by checking for specific content or status
        response=$(curl -s -w "%{http_code}" -o /dev/null https://reforestation-management.onrender.com/)
        
        if [ "$response" -ne 200 ]; then
          echo "Site not fully loaded, HTTP code: $response"
          exit 1  # Fail the job if the page is not fully loaded
        else
          echo "Site is fully loaded with HTTP code: $response"
        fi
